### ISSUE TITLE
Documentation partial rewriting

### ISSUE THREAD

**Issue by csidyel** [semaphoreci/docs#1079]
### List of the documentation pages that will be updated and their progress:

- [x] /ci-cd-environment/docker-layer-caching/ [ ]
- [x] /reference/pipeline-yaml-reference/
- [x] /guided-tour/getting-started/
- [x] /examples/using-docker-compose-in-ci/
- [x] /reference/sem-command-line-tool/
- [x] /reference/conditions-reference/
- [x] /examples/pushing-docker-images-to-google-container-registry-gcr/
- [x] /ci-cd-environment/machine-types/
- [x] /essentials/caching-dependencies-and-directories/
- [x] /essentials/concepts/
- [x] /ci-cd-environment/environment-variables/
- [x] /examples/tutorials-and-example-projects/
- [x] /reference/secrets-yaml-reference/
- [x] /faq/faq/
- [x] /essentials/building-monorepo-projects/
- [x] /examples/pushing-docker-images-to-aws-elastic-container-registry-ecr/
- [x] /examples/deploying_with_git_deploy/
- [x] /reference/api-v1alpha/
- [x] /account-management/connecting-github-and-semaphore/
- [x] /ci-cd-environment/custom-ci-cd-environment-with-docker/
- [x] /examples/node-js-and-typescript-continuous-integration/
- [x] /reference/semaphore-changelog/
- [x] /essentials/deploying-with-promotions/
- [x] /essentials/skip-building-some-commits-with-ci-skip/
- [x] /essentials/debugging-with-ssh-access/
- [x] /ci-cd-environment/working-with-docker/
- [x] /essentials/project-workflow-trigger-options/
- [x] /essentials/artifacts/
- [x] /ci-cd-environment/ubuntu-18.04-image/
- [x] /essentials/environment-variables/
- [x] /essentials/modeling-complex-workflows/
- [x] /account-management/organizations/
- [x] /essentials/using-secrets/
- [x] /ci-cd-environment/macos-xcode-12-image/
- [x] /programming-languages/javascript-and-node-js/
- [x] /examples/using-terraform-with-google-cloud/
- [x] /examples/golang-continuous-integration/
- [x] /reference/toolbox-reference/
- [x] /essentials/test-summary/
- [x] /examples/google-cloud-run-continuous-deployment/
- [x] /programming-languages/ruby/
- [x] /examples/rails-continuous-integration/
- [x] /programming-languages/android/
- [x] /ci-cd-environment/install-self-hosted-agent/
- [x] /examples/code-signing-for-ios-projects/
- [x] /account-management/checking-the-connection-between-github-and-semaphore-2.0/
- [x] /examples/heroku-deployment/
- [x] /ci-cd-environment/sem-service-managing-databases-and-services-on-linux/
- [x] /ci-cd-environment/ubuntu-20.04-image/
- [x] /ci-cd-environment/docker-authentication/
- [x] /ci-cd-environment/semaphore-registry-images/
- [x] /essentials/schedule-a-workflow-run/
- [x] /examples/django-continuous-integration/
- [x] /examples/ios-continuous-integration-with-xcode/
- [x] /examples/laravel-php-continuous-integration/
- [x] /ci-cd-environment/self-hosted-agents-overview/
- [x] /ci-cd-environment/choosing-between-a-vm-and-docker-based-environment/
- [x] /ci-cd-environment/job-isolation.md
- [x] /essentials/fail-fast-stop-running-tests-on-the-first-failure/
- [x] /reference/projects-yaml-reference/
- [x] /ci-cd-environment/configuring-database-access/
- [x] /reference/quotas-and-limits/
- [x] /essentials/pipeline-queues/
- [x] /examples/ci-cd-for-microservices-on-kubernetes/
- [x] /account-management/permission-levels/
- [x] /essentials/auto-cancel-previous-pipelines-on-a-new-push/
- [x] /ci-cd-environment/aws-support/
- [x] /ci-cd-environment/install-self-hosted-agent/
- [x] /examples/continuous-deployment-of-a-static-website/
- [x] /reference/artifact-cli-reference/
- [x] /essentials/slack-notifications/
- [x] /reference/jobs-yaml-reference/
- [x] /programming-languages/python/
- [x] /ci-cd-environment/macos-xcode-11-image/
- [x] /reference/notifications-yaml-reference/
- [x] /examples/deployment-to-aws-elastic-beanstalk/
- [x] /reference/test-results-cli-reference/
- [x] /ci-cd-environment/sem-version-managing-language-versions-on-linux/
- [x] /programming-languages/php/
- [x] /reference/dashboards-yaml-reference/
- [x] /essentials/configuring-github-status-checks/
- [x] /essentials/using-private-dependencies/
- [x] /ci-cd-environment/setup-caching-on-aws-s3/
- [x] /account-management/billing/
- [x] /essentials/build-matrix/
- [x] /essentials/webhook-notifications/
- [x] /examples/change-based-execution-for-monorepos/
- [x] /examples/deploy-to-digitalocean/
- [x] /essentials/deployment-dashboards/
- [x] /programming-languages/go/
- [x] /ci-cd-environment/configure-self-hosted-agent/
- [x] /essentials/prioritization/
- [x] /ci-cd-environment/flutter/
- [x] /examples/java-spring-continuous-integration/
- [x] /programming-languages/cpp/
- [x] /account-management/plans/
- [x] /faq/migration-guide-for-semaphore-classic-users/
- [x] /programming-languages/java/
- [x] /examples/netlify-continuous-deployment/
- [x] /ci-cd-environment/self-hosted-agent-types/
- [x] /essentials/tag-triggered-deployment/
- [x] /essentials/status-badges/
- [x] /examples/elixir-phoenix-continuous-integration/
- [x] /examples/scala-play-continuous-integration/
- [x] /ci-cd-environment/agent-migration-to-ubuntu2004/
- [x] /examples/zeit-now-continuous-deployment/
- [x] /ci-cd-environment/android-images/
- [x] /faq/managing-projects/
- [x] /account-management/discounts/
- [x] /examples/testflight-ios-app-distribution/
- [x] /account-management/working-with-github-sso/
- [x] /examples/download-and-cache-a-custom-file/
- [x] /ci-cd-environment/macos-xcode-13-image/
- [x] /examples/configuring-parallel-tests-with-code-climate/
- [x] /programming-languages/swift/
- [x] /examples/clojure-luminus-ci-cd/
- [x] /examples/publishing-docker-images-on-dockerhub/
- [x] /programming-languages/rust/
- [x] /ci-cd-environment/nested-virtualization/
- [x] /programming-languages/scala/
- [x] /programming-languages/c/
- [x] /programming-languages/elixir/
- [x] /programming-languages/clojure/
- [x] /examples/hockeyapp-ios-app-distribution/
- [x] /programming-languages/erlang/
- [x] /essentials/caching-dependencies-and-directories.md

**Comment by csidyel** [comment]
Pipeline reference updated: https://github.com/semaphoreci/docs/pull/1086

**Comment by csidyel** [comment]
Getting started: https://github.com/semaphoreci/docs/pull/1092

**Comment by csidyel** [comment]
Caching dependencies, concepts, environment variables: https://github.com/semaphoreci/docs/pull/1103

**Comment by csidyel** [comment]
https://github.com/semaphoreci/docs/pull/1106
tutorials-and-example-projects.md
secrets-yaml-reference.md
faq.md
building-monorepo-projects.md
pushing-docker-images-to-aws-elastic-container-registry-ecr.md
deploying_with_git_deploy.md

**Comment by csidyel** [comment]
https://github.com/semaphoreci/docs/pull/1114
node-js-and-typescript-continuous-integration 
changelog

**Comment by csidyel** [comment]
13 new pages added: https://github.com/semaphoreci/docs/pull/1117

**Comment by GabrielaG08** [comment]
hey @csidyel :) I've counted 102 pages left.

**Comment by csidyel** [comment]
6 new pages: https://github.com/semaphoreci/docs/pull/1118

**Comment by csidyel** [comment]
8 new pages added: https://github.com/semaphoreci/docs/pull/1121

**Comment by csidyel** [comment]
8 pages added: https://github.com/semaphoreci/docs/pull/1129

**Comment by csidyel** [comment]
1 page added: https://github.com/semaphoreci/docs/pull/1133

**Comment by csidyel** [comment]
Caching added: https://github.com/semaphoreci/docs/pull/1127
Clojure added: https://github.com/semaphoreci/docs/pull/1140
Elixir added: https://github.com/semaphoreci/docs/pull/1141

**Comment by csidyel** [comment]
C added: https://github.com/semaphoreci/docs/pull/1142
Scala added: https://github.com/semaphoreci/docs/pull/1143
Nested virtualization: https://github.com/semaphoreci/docs/pull/1144

**Comment by csidyel** [comment]
Rust: https://github.com/semaphoreci/docs/pull/1145

**Comment by csidyel** [comment]
13 new pages added: https://github.com/semaphoreci/docs/pull/1147

**Comment by csidyel** [comment]
Erlang added: https://github.com/semaphoreci/docs/pull/1132

**Comment by csidyel** [comment]
4 new pages added: https://github.com/semaphoreci/docs/pull/1150

**Comment by csidyel** [comment]
11 new pages: https://github.com/semaphoreci/docs/pull/1154

**Comment by csidyel** [comment]
22 pages added: https://github.com/semaphoreci/docs/pull/1167

**Comment by csidyel** [comment]
@GabrielaG08 @markoa 

This task has been completed. I'm closing the issue. If there are more or new pages that need to be reviewed, it can be done in a separate task.

**Comment by markoa** [comment]
Well done!
