### ISSUE TITLE
Backslash in page ToC

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#1093]
https://docs.semaphoreci.com/reference/pipeline-yaml-reference/

<img width="260" alt="Screen Shot 2021-11-09 at 5 22 27 PM" src="https://user-images.githubusercontent.com/8651/140963452-344734a9-d3c9-4ac0-8b0e-9892c07d807a.png">

**Comment by AleksandarCole** [comment]
I'll update the docs page. Assigned @shiroyasha for manual deployment when we have time. Will leave a link to the PR when ready.

**Comment by shiroyasha** [comment]
Fixed in the latest release.
