### ISSUE TITLE
Implement Table of Contents

### ISSUE THREAD

**Issue by mimimalizam** [semaphoreci/docs#12]

**Comment by mactsouk** [comment]
Would that be possible to decide which documentation pages will have a TOC and which will not?

**Comment by mimimalizam** [comment]
Sadly I don't have an answer at the moment.

For the time being, I'd like to suggest using markdown headings on pages for which including ToC is necessary.

Here is an example: 
- [markdown file](https://github.com/semaphoreci/docs/blob/d6db51674e5693c672e9199c928ce6934fff9d4a/ubuntu-1804-image_5b461f730428630abc0bf442.md)  
- [its raw content](https://raw.githubusercontent.com/semaphoreci/docs/d6db51674e5693c672e9199c928ce6934fff9d4a/ubuntu-1804-image_5b461f730428630abc0bf442.md)
- [article on helpscout](https://docs.semaphoreci.com/article/32-ubuntu-1804-image#installed-software)

It can be created it as follows. If there is a heading/title/subtitle  (e.g. `### Example title or subtitle`) you'll add `- [Example title or subtitle](#example-title-or-subtitle)` to the ToC. This will create link to title/subtitle in article.

Also, you can use different md elements to differentiate title and subtitle. For example,  

`- [Example title](#example-title)` - for title
`  * [Example subtitle](#example-subtitle)` - for subtitle

I've added these to the agent article as an examle - feel free to change it :)
([doc on helpscout](https://docs.semaphoreci.com/article/23-agent), [markdown file in repository](https://github.com/semaphoreci/docs/blob/ed9607d483139a5426296f9d7e1dee4cbc38c14c/agent_5b2500d02c7d3a0fa9a3110f.md), [raw](https://raw.githubusercontent.com/semaphoreci/docs/ed9607d483139a5426296f9d7e1dee4cbc38c14c/agent_5b2500d02c7d3a0fa9a3110f.md) )

**Comment by shiroyasha** [comment]
@mimimalizam In Semaphore 1.0, I've created a `toc` helper for markdown files https://github.com/renderedtext/semaphore-docs-new/blob/90c40594a3a72d9ef3237e6373b2ce12bc68578c/source/docs_helpers.rb.

With the helper, if you want a table of content on a particualar page, you can put:

```
<%= toc %>
```

anywhere on the page. Example: https://github.com/renderedtext/semaphore-docs-new/blob/43277f36408cd482f95a7e4a1713c803b6e7cd77/source/docs/cli-secrets.md.erb#L12.

Not sure if it can be used in this context. Let me know if it helps.

**Comment by mimimalizam** [comment]
tnx for pointing it out @shiroyasha 👏 🏆 

After consulting @darkofabijan, we have decided to work on the programmatic implementation at some point next week (or during the week after).

In the meantime, please create the toc manually for pages where you find it necessary. @mactsouk

**Comment by mactsouk** [comment]
Creating the TOC manually. I will also create a separate document in the repo to explain the way.

**Comment by markoa** [comment]
I don't think we need this, writing ToCs manually wasn't so bad and can have useful effects as it makes you think about the structure of the page. Closing. :)
