### ISSUE TITLE
macos-xcode14 image

### ISSUE THREAD

**Issue by ihnatmoisieiev** [semaphoreci/docs#1245]
Hello Team,

please add a new version of the Xcode ASAP - 14.0. It's blocking our development processes. 

Thank you!

**Comment by ihnatmoisieiev** [comment]
Any updates?

**Comment by ivanaur** [comment]
Hey, @ihnatmoisieiev . Our platform team is working on the Xcode 14 as we speak, it will be available at the beginning of next week. We'll make sure to keep you posted!

**Comment by lucianomlima** [comment]
It's available now!
