### ISSUE TITLE
Add note that services aren’t shared between blocks

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#131]
This came up a few times on support. Let’s make it more clear that a database or any service isn't shared between blocks and users need to start them within each block and migrate / populate data. 

Pages to update:
- https://docs.semaphoreci.com/article/32-ubuntu-1804-image#databases-and-services
- https://docs.semaphoreci.com/article/65-customizing-the-build-environment

**Comment by mactsouk** [comment]
@markoa Shall I do that?

**Comment by markoa** [comment]
@mactsouk please go ahead

**Comment by mactsouk** [comment]
https://github.com/semaphoreci/docs/pull/143
