### ISSUE TITLE
Ubuntu image documentation needs to be updated for new machine types

### ISSUE THREAD

**Issue by betelgeuse** [semaphoreci/docs#1314]
https://docs.semaphoreci.com/ci-cd-environment/ubuntu-18.04-image/

"The ubuntu1804 image can be used in combination with all Linux machine types: e1-standard-2, e1-standard-4, and e1-standard-8."

The list of Linux machine types is longer (e2 and f1) so the word "all" here no longer works.

https://docs.semaphoreci.com/ci-cd-environment/machine-types/

"Linux machine types can be paired with [Ubuntu 18.04 image](https://docs.semaphoreci.com/ci-cd-environment/ubuntu-18.04-image/), [Ubuntu 20.04 image](https://docs.semaphoreci.com/ci-cd-environment/ubuntu-20.04-image/), and [Docker-based environment](https://docs.semaphoreci.com/ci-cd-environment/custom-ci-cd-environment-with-docker/)."

This text needs a revision since 18.04 can't be paired with all the new machine types.

**Comment by csidyel** [comment]
Thank you for sharing this. I changed the text to 
```
The ubuntu1804 image can be used in combination with the following Linux machine types: e1-standard-2, e1-standard-4, and e1-standard-8.
```
