### ISSUE TITLE
SEMAPHORE_WORKFLOW_ID description is confusing.

### ISSUE THREAD

**Issue by darkofabijan** [semaphoreci/docs#137]
> The value of the SEMAPHORE_WORKFLOW_ID environment variable is the ID of the workflow of the current job.

`of the current job.` part

**Comment by mactsouk** [comment]
@darkofabijan Updated it to:

`The value of the SEMAPHORE_WORKFLOW_ID environment variable is the workflow
ID that is used during the execution of the active job.`
