### ISSUE TITLE
Issue loading disruption occurrencies / test details (without any clues)

### ISSUE THREAD

**Issue by dimitar-peychinov** [semaphoreci/docs#1438]
The title says it all, here's a screenshot:
<img width="1758" alt="Screenshot 2024-05-20 at 16 18 45" src="https://github.com/semaphoreci/docs/assets/169891028/434b36c0-31d1-439b-a830-859f71c1dc83">

**Comment by mateuscap** [comment]
Hi @dimitar-peychinov, would you be so kind as to submit a[ request through this link](https://support.semaphoreci.com/hc/en-us/requests/new) so we can further investigate?

Since this report is not related to the docs I'll go ahead and close it.
