### ISSUE TITLE
No mention to the -N option in the command `test-results publish`

### ISSUE THREAD

**Issue by diaclavijo** [semaphoreci/docs#1454]
Hello, 

Here https://docs.semaphoreci.com/essentials/test-summary/#setting-up-test-reports it is mentioned in the video that you can pass the -N argument to the `test-results publish` to tag the results for a certain job. 

Nevertheless in the written communication this is not mention at all.

**Comment by skipi** [comment]
👋🏻 @diaclavijo, thanks for the feedback.

In the [See also](https://docs.semaphoreci.com/essentials/test-summary/#see-also) section, you can find a link to the `Test Results CLI` page. More details about available flags can be found there.

Additionally, we have repository documentation available for the Test Results CLI [here](https://github.com/semaphoreci/test-results/tree/master). However, I've noticed that this repository is not referenced in the documentation. We will add it for better visibility.
