### ISSUE TITLE
How to cache rbenv directory with additional Ruby versions

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#178]
Use case is when a user installs a Ruby version which is not preinstalled on Semaphore. This is a time-consuming operation since it involves download over network and compilation. They want to do it once and keep the stuff available in cache "forever". Let's add a recipe for that using `cache` to the [Ruby guide](https://docs.semaphoreci.com/article/73-ruby). Over time we can add similar tip for other languages too.

**Comment by darkofabijan** [comment]
@mactsouk @markoa this just became obsolete by this - https://github.com/semaphoreci/docs/issues/216. We now support all versions of Ruby that were ever shipped. Same is true for PHP, not for other languages yet.

Plan is to support also other languages and versions over time. Depends on popular demand. 

For reference this is the implementation - https://github.com/semaphoreci/toolbox/pull/47/files

**Comment by Willis0826** [comment]
Hi @darkofabijan , the ruby version 2.5.7 seems not be included in preinstalled list by Semaphore.
Any chance I can install the ruby 2.5.7 with cache?
Thanks for advices.

**Comment by pedromamede** [comment]
> Hi @darkofabijan , the ruby version 2.5.7 seems not be included in preinstalled list by Semaphore. Any chance I can install the ruby 2.5.7 with cache? Thanks for advices.

@Willis0826 have you found a solution for this?

**Comment by pedromamede** [comment]
Not sure if this is the right place to share this but in case anyone is interested in a solution:

1. Use these commands to install and store
```
   sem-version ruby 2.5.5
   cache store <key-name> ~/.rbenv/versions/2.5.5
```

2. Use these commands to restore and switch to the right version
````
   cache restore <key-name>
```
