### ISSUE TITLE
Provide troubleshooting tips for sem init

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#180]
For example, we sometimes receive a message like
> I've been trying to add a project to Semaphore. Unfortunately, using `sem init` appears not to work appropriately, since on both my machine, as well as the machine of a Git admin, running `sem init` fails with `"{"message":"admin permisssions are required on the repository in order to add the project to Semaphore"}"`.

Raw response:
> In order to add a project to Semaphore 2.0, the user must be a member of your Semaphore 2.0 organization and also have Admin permission level for the project on GitHub.
Currently, Semaphore is "mirroring" permission rights from GitHub which means that a user will have the same level of permission on Semaphore 2.0 as on GitHub.
>
> Also, if the person has Admin permission level on GitHub and is a member of your Semaphore 2.0 organization and still cannot add a project, could you please check if the access for Semaphore 2.0 was granted within your GitHub organization? You can check that here: https://github.com/settings/connections/applications/328c742132e5407abd7d. 
If it has been granted, there should be a green checkmark next to your organization name. If there isn't one, that means that the access hasn't been granted for Semaphore 2.0 and you cannot add a project to it.

We'd add a potentially more concise explanation and any other similar FAQ to the [guided tour](https://docs.semaphoreci.com/article/63-your-first-project).

**Comment by markoa** [comment]
@ssamardzic @ivanaur when you have time please post if you've seen any other repeating issue related to `sem init`.

**Comment by ivanaur** [comment]
The same response can be used in following situation:

> I am getting this whenever I try to start a new project:
> 
> i9:projectname(master): sem init
> error: http status 422 with message "{"message":"POST https://api.github.com/repos/orgname/projectname/keys: 404 - Not Found // See: https://developer.github.com/v3/repos/keys/#add-a-new-deploy-key";}" received from upstream

**Comment by markoa** [comment]
Tips added to https://docs.semaphoreci.com/article/63-your-first-project.
