### ISSUE TITLE
Provide information about default SSH session duration and charging

### ISSUE THREAD

**Issue by fbrdaric** [semaphoreci/docs#194]
Should be added here: https://docs.semaphoreci.com/article/75-debugging-with-ssh-access#stopping-a-debug-session.

**Comment by shiroyasha** [comment]
The duration of SSH sessions are explained on the top of the page. https://docs.semaphoreci.com/article/75-debugging-with-ssh-access#exploring-the-build-environment.

**Comment by fbrdaric** [comment]
@shiroyasha thanks 🙇‍♂️

**Comment by shiroyasha** [comment]
On the other hand, repeting this information in the stopping section wouldn't hurt.
