### ISSUE TITLE
Update sem reference for 0.8.14

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#200]
I'm not sure which version was the last one documented. There were few but important additions in the last few releases.

**Comment by shiroyasha** [comment]
@mactsouk @markoa I've added a curl to the CLI release pipeline to create an issue in this repository for each new release. I hope it will make this process a bit more streamlined. 

Example from latest release https://github.com/semaphoreci/docs/issues/204.

**Comment by mactsouk** [comment]
Closed by https://github.com/semaphoreci/docs/issues/204.
