### ISSUE TITLE
Fix typo in "Getting started" guide

### ISSUE THREAD

**Issue by ssamardzic** [semaphoreci/docs#206]
A user reported a typo in the first sentence of the first paragraph of Getting started guide. He said: 

> Please fix the first sentence in your "getting started" paragraph. There is no such word as its'.

Also, I've noticed we're missing one word in the second sentence of the same paragraph. 

_If you're new to Semaphore or have limited Semaphore experience, then this the best place to start._
should be
_If you're new to Semaphore or have limited Semaphore experience, then this **is** the best place to start._

**Comment by mactsouk** [comment]
Made the corrections to `master` branch.
