### ISSUE TITLE
Uploading artifacts to AWS S3

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#212]
Artifacts are a frequently searched term on both S1 and S2 docs. We can provide steps how to use S3 buckets as artifacts storage. Combines using secrets, preinstalled aws cli and promotions.

```
aws s3 cp path-to-artifacts-dir/ s3://my-bucket/artifacts --recursive
```

**Comment by ahawkins** [comment]
I'm on this

**Comment by markoa** [comment]
Note: this should be a new page.

**Comment by markoa** [comment]
Deprecated with an upcoming feature.
