### ISSUE TITLE
Document how to change the editor for `sem edit ...`

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#213]
Based on an issue in the CLI repository https://github.com/semaphoreci/cli/issues/131.

**Comment by mactsouk** [comment]
@markoa @shiroyasha Should I put it in `sem` reference or just create a new recipe page?
My vote goes to "create a new recipe page".

**Comment by shiroyasha** [comment]
Now, starting from version `v0.8.17`, the CLI support the EDITOR environment variable for setting up the editor.

Another new feature is that now we support editors that need flags to stay open, such as sublime with `subl --wait`.
