### ISSUE TITLE
How to build & test TypeScript code

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#214]
Add a section to the [JavaScript page](https://docs.semaphoreci.com/article/82-language-javascript-and-nodejs) which shows an example configuration. I propose writing a `.semaphore.yml` which would run [this official example project](https://github.com/Microsoft/TypeScript-Node-Starter).

**Comment by ahawkins** [comment]
@markoa I can take this

**Comment by markoa** [comment]
Resolved with https://docs.semaphoreci.com/article/121-nodejs-typescript-continuous-integration.
