### ISSUE TITLE
Extend page on publishing a Docker image to DockerHub

### ISSUE THREAD

**Issue by darkofabijan** [semaphoreci/docs#245]
https://docs.semaphoreci.com/article/70-dockerhub

Has only docker-compose example of pushing. It should also include a simple "docker push" example.

**Comment by markoa** [comment]
Received some feedback via support in which people observed that the page doesn't give any example of how to configure a docker-compose yml file to use docker-compose push. So they struggle. We are verbose about how to create a secret, we should also be about configuring docker compose and explain the outcomes of example pipeline.

**Comment by markoa** [comment]
Closing as stale.
