### ISSUE TITLE
Documentation page for "Auto deploy on git tag or new release on GitHub"

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#275]
Tl;dr: We should explain how to trigger a deployment when you tag a particular commit in Github.

Additional details in the following support case https://github.com/renderedtext/issues/issues/1391.

**Comment by markoa** [comment]
We use this exact flow to release new versions of our CLI:

Promotion definition in the main semaphore.yml file: https://github.com/semaphoreci/cli/blob/master/.semaphore/semaphore.yml#L44

The promoted pipeline YAML file: https://github.com/semaphoreci/cli/blob/master/.semaphore/edge.yml.

**Comment by DamjanBecirovic** [comment]
This is done, and here is the page https://docs.semaphoreci.com/article/165-tag-triggered-deployment
