### ISSUE TITLE
Document how to change/add new database users; How to configure database started with sem-service

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#295]
Noticed this question on support. Docs should cover it.

Metacode for this behaviour:

``` bash
sem-service start postgres
psql -h postgres@localhost -c "CREATE USER developer WITH PASSWORD 'developer';
psql -h postgres@localhost -c "ALTER USER developer WITH SUPERUSER;"
```

the above adds an additional `developer` superuser db account to postgres.

**Comment by shiroyasha** [comment]
The above is a good pattern for all database configuration that you need in your tests.

- timezone settings
- usernames, privilages
- encoding settings
- etc...

Would fit nicely in as a "Configuring the database" section of a postgres documentation page.

**Comment by mactsouk** [comment]
@shiroyasha Should I cover all databases found in https://docs.semaphoreci.com/article/32-ubuntu-1804-image#databases-and-services?

**Comment by shiroyasha** [comment]
Good question. Leaving this decision and direction of this proposal to @markoa.

**Comment by markoa** [comment]
I'd start a new page _Configuring database access_. Keep the Ubuntu image section on the level of only listing what's available and linking to that page.

**Comment by mactsouk** [comment]
@markoa @shiroyasha I will start a new doc page under the `CI/CD Environment` section.
