### ISSUE TITLE
Make it clear which machine types can run ubuntu1804, and which of them can run macos-mojave

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#297]
Continuation of this document https://github.com/semaphoreci/docs/pull/296.

One option is to introduce this distinction in the reference here: https://docs.semaphoreci.com/article/50-pipeline-yaml#agent, but that part of the documentation is a bit hidden for first time Semaphore users.

**Comment by shiroyasha** [comment]
@markoa I'll need your input on this one. 🙇 

It might need a bit f restructuring in the documentation layout.

**Comment by markoa** [comment]
I propose that:
- [MacOS reference page](https://github.com/semaphoreci/docs/issues/298) has a sentence on top which says something like "_This operating system image can be used with Apple machine types_", where "Apple machine types" is a link to sub-header on the [Machine Types](https://docs.semaphoreci.com/article/20-machine-types) page.
- [Ubuntu1804](https://docs.semaphoreci.com/article/32-ubuntu-1804-image) page has a similar sentence pointing to Linux-based machine types.
- We also summarize Mac and Linux options in [Concepts](https://docs.semaphoreci.com/article/62-concepts).

After the above is completed, I suppose that it will become clear how exactly to word the update to the Agent/mt sections in Pipeline YML reference.
