### ISSUE TITLE
Adapt reference YML snippets to syntax highlighting

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#315]
Many pages written in the early days, most notably in Reference, are using the indentation method to produce code snippets. As a result, these snippets don't get syntax highlighting. We need all those snippets to be re-formatted with tags which will [enable syntax highlighting](https://github.com/semaphoreci/docs/blob/master/CONTRIBUTING.md#text-formatting):

```
<pre><code class="language-yaml"># code goes here (start on this line, not below)
</code></pre>
```

**Comment by shiroyasha** [comment]
Fixed in:

- https://github.com/semaphoreci/docs/pull/353
- https://github.com/semaphoreci/docs/pull/354
