### ISSUE TITLE
Results filter has been added for Slack notifications

### ISSUE THREAD

**Issue by mimimalizam** [semaphoreci/docs#316]
We have implemented the results filter for Slack notifications recently.
Allowed values for the results filter are: `passed`, `failed`, `stopped`, `canceled`

Example yaml 
```
apiVersion: v1alpha
kind: Notification
metadata:
  name: example-notif-name
spec:
  rules:
    - name: "Example"
      filter:
        projects:
          - example-project
        results:
          - passed
          - failed
      notify:
        slack:
          endpoint: https://hooks.slack.com/services/xxx/yyy/zzz
```

**Comment by markoa** [comment]
This should be added to what is currently the "Advanced" section, since the CLI currently doesn't support this option.
