### ISSUE TITLE
Document how to debug on Mac machines

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#318]
When you type:

```
sem debug project [name]
```

by default we run `e1-standard-2/ubuntu1804` machine. If you want to run other machine types you need to specify it via flags.

Needs to be clarified here: 

https://docs.semaphoreci.com/article/75-debugging-with-ssh-access#exploring-the-build-environment

---

Note: This only applies when you are debugging on a project level.

If you run `sem debug job <id>` it will use the machine defined in that job.

---

Note2: In the future, we can introduce some magic like:

1. If this project had at least one executed workflow -> use the machine type from the latest workflow
2. If not, fallback to the `e1-standard-2/ubuntu1804`

**Comment by markoa** [comment]
@shiroyasha I need help here:

```
$ sem debug project  semaphore-demo-ios-swift-xcode --machine-type a1-standard-4
* Creating debug session for project 'semaphore-demo-ios-swift-xcode'
* Setting duration to 60 minutes
* Waiting for debug session to boot up .
Error while starting SSH session Job. Debug Job '3e57353e-cbac-44e3-b27a-20e796877aeb' is in finished state.
```

(I'm the right context.)

I wasn't aware that `sem debug project` works only if you have jobs in running state. Is this true?

It yes then we need to [update docs accordingly](https://docs.semaphoreci.com/article/53-sem-reference#sem-debug-for-projects). And frankly I don't understand why we'd recommend this action as the first step in the debugging guide, and not `sem debug job`...

**Comment by shiroyasha** [comment]
Clarification about the message:

> Debug Job '3e57353e-cbac-44e3-b27a-20e796877aeb' is in finished state.

Means that when we want to connect to the debug job, it is in the finished state. This happens when the initialization of the debug job fails.

The message needs to be more clear. For example:

> Failed to start the debug session. 

+ additional details if they exist.

**Comment by SohaibAnwaar** [comment]
@shiroyasha  Hope you are doing good. Actually I started a semaphore project job and it's been 20 mins I have no log about the job and the job is still running. How can I get the log so that I can track the progress?


```
sem debug job aa3e76ea-73c8-439d-8344-16d7bcf25e22

* Creating debug session for job 'aa3e76ea-73c8-439d-8344-16d7bcf25e22'
* Setting duration to 60 minutes
* Waiting for debug session to boot up ......................................................................................................................................................................................................................................................................................................................^
```

**Comment by SohaibAnwaar** [comment]
Sorry alot of duplicate jobs are running you can check your jobs 
1 Connect to semaphore cli with your local terminal, connect to your semaphore and run command 
`sem get jobs`
and to stop all the jobs you can run this command
`sem get jobs | awk {'print $1'} | xargs -I {} sem stop jobs {}`
and

**Comment by markoa** [comment]
Closing as stale.
