### ISSUE TITLE
Extra empty line on top of code examples

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#335]
<img width="732" alt="Screen Shot 2019-03-13 at 6 30 44 PM" src="https://user-images.githubusercontent.com/1779493/54300944-39f57080-45be-11e9-9de3-3c2b57664f05.png">

**Comment by markoa** [comment]
Thanks. I recommend just editing the file and committing straight to master for such trivial changes, it should take the same amount of time as submitting this issue. :)

**Comment by shiroyasha** [comment]
:D

I see your point. I thought that it was the case for all code examples, not only this one page.

I'll edit.

**Comment by shiroyasha** [comment]
Edited.

It's a bit weird that we need to put it on the same line:

https://github.com/semaphoreci/docs/commit/e45dd0db720f528c0e494f02fc14e197f8577794

I wonder why.
