### ISSUE TITLE
Document sem create secret -e

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#374]
https://github.com/semaphoreci/cli/releases/tag/v0.10.0

-> sem reference `sem-reference_5b6968642c7d3a03f89d6bff.md`

**Comment by shiroyasha** [comment]
It should be this one if I am correct. https://github.com/semaphoreci/docs/pull/366

**Comment by markoa** [comment]
Yes, sorry. I searched for `sem create -e` on the page but that's not the right way to find it.
