### ISSUE TITLE
Simpler examples to create MySQL users

### ISSUE THREAD

**Issue by weshooper** [semaphoreci/docs#393]
https://docs.semaphoreci.com/article/118-configuring-database-access#mysql

No need to create the `.sql` files and pipe them in, simpler to use the `-e` parameter:

```
# example 1:
mysql -h 127.0.0.1 -P 3306 -u root -e "CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';"

# example 2:
mysql -h 127.0.0.1 -P 3306 -u root -e "CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'newuser'@'localhost';"
```

Additionally, I'm fairly sure that `127.0.0.1` should be used, rather than `localhost` in the examples.

**Comment by markoa** [comment]
localhost == 127.0.0.1

Updated, good idea and thank you for sharing!
