### ISSUE TITLE
List of Pre-built convenience Docker images for Semaphore CI/CD jobs is not up to date

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#411]

**Comment by CommanderK5** [comment]
Here you go:

https://hub.docker.com/r/semaphoreci/python/tags
https://hub.docker.com/r/semaphoreci/android/tags
https://hub.docker.com/r/semaphoreci/ruby/tags
https://hub.docker.com/r/semaphoreci/haskell/tags
https://hub.docker.com/r/semaphoreci/ubuntu/tags
https://hub.docker.com/r/semaphoreci/rust/tags
https://hub.docker.com/r/semaphoreci/golang/tags

**Comment by shiroyasha** [comment]
@CommanderK5 thanks. Please open a PR with the updates in this document https://github.com/semaphoreci/docs/blob/master/custom-ci-cd-environment-with-docker_5caf3f432c7d3a392f9ceb50.md#pre-built-convenience-docker-images-for-semaphore-cicd-jobs.

**Comment by CommanderK5** [comment]
merged in https://github.com/semaphoreci/docs/pull/416
