### ISSUE TITLE
Code Climate integration recipe

### ISSUE THREAD

**Issue by fbrdaric** [semaphoreci/docs#451]
Our proposed solution on integrating with a code coverage tool should be in place.

**Comment by fbrdaric** [comment]
@rtgkurel @csidyel Can you pls take care of that?

**Comment by Ivana-Markovic** [comment]
@csidyel just checking if there are any updates on this :)

**Comment by csidyel** [comment]
PR created: https://github.com/semaphoreci/docs/commit/488db520b4ea9ca3342aa30fb7a7c06d99459783
