### ISSUE TITLE
Request the org owner to give access to Semaphore

### ISSUE THREAD

**Issue by Ivana-Markovic** [semaphoreci/docs#459]
Related to: https://github.com/renderedtext/issues/issues/2260

Can you please update the Semaphore 2.0 docs based on the comments from the related support case. We can work on this together if needed.

**Comment by ivanaur** [comment]
We have that as the last point here: https://docs.semaphoreci.com/article/63-your-first-project#troubleshooting. Do you want us to add "how to request approval from the owner" part? That's more GH than S2, that's why I'm asking.

**Comment by Ivana-Markovic** [comment]
Yes, I think Filip wanted to add this too, even though it is GH related (he has probably been asked about this more than once, I assume and in this case, it is good to cover it in the docs).

**Comment by ivanaur** [comment]
https://github.com/semaphoreci/docs/pull/470
