### ISSUE TITLE
Document how-tos that have to be done by us

### ISSUE THREAD

**Issue by Ivana-Markovic** [semaphoreci/docs#460]
Related support case: https://github.com/renderedtext/issues/issues/2267

We basically need to say if you need help with XYZ, please contact us at support@semaphoreci.com (we already have some similar parts where we advise users to ask us for help)

**Comment by Ivana-Markovic** [comment]
This might be related too: https://github.com/renderedtext/issues/issues/2277

**Comment by ivanaur** [comment]
https://github.com/semaphoreci/docs/pull/474
