### ISSUE TITLE
It appears that ' is not parsed nicely

### ISSUE THREAD

**Issue by mimimalizam** [semaphoreci/docs#5]
Example found on these pages:

[markdown file](https://github.com/semaphoreci/docs/blob/master/5b461f730428630abc0bf442_ubuntu-1804-image.md#databases) `don't` 
[helpscout docs](https://docs.semaphoreci.com/article/32-ubuntu-1804-image) `don\'t `

**Comment by markoa** [comment]
I've never noticed this, it probably sorted itself long time ago. :)
