### ISSUE TITLE
Feedback from a customer: cache doesn't overwrite existing keys.

### ISSUE THREAD

**Issue by csidyel** [semaphoreci/docs#505]
Based on this conversation: https://secure.helpscout.net/conversation/935469757/21540/

It seems this command for storing creates confusion because the cache mechanism doesn't overwrite existing keys: `cache store website-build public`

Can this be modified?

https://docs.semaphoreci.com/article/97-continuous-deployment-static-website

**Comment by markoa** [comment]
No. This use case is more suitable for artifacts. We used cache as second-best option. User needs to wait just a little bit more... :)
