### ISSUE TITLE
The reference part of the docs is oversaturated with `property`

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#619]
Not really sure how to document this issue, but here it goes...

It feels like every Nth word in the reference part of the docs is `property`. It is "mathematically correct", but not the most pleasant to read.

<img width="826" alt="Screen Shot 2019-12-16 at 2 29 13 PM" src="https://user-images.githubusercontent.com/1779493/70910678-74d67a00-2010-11ea-90c0-d927f11abed0.png">

**Comment by CCIT652** [comment]
Swift invention

**Comment by markoa** [comment]
Closing as stale.
