### ISSUE TITLE
502 Error after deployment

### ISSUE THREAD

**Issue by Ivana-Markovic** [semaphoreci/docs#623]
@CommanderK5, Darko and I deployed some changes on http://docsv2.semaphoreci.com and after each deployment, there was a 502 error, could you please fix it as soon as you can?

Please ping me or @darkofabijan if you need further clarification.

Thanks!

**Comment by darkofabijan** [comment]
I can add that it's likely caused by the lack of liveness and readiness probes. 502 are happening randomly during deployment and then 2 mins later as pods are rotated its all good.

**Comment by CommanderK5** [comment]
Yes, I've asked Igor what is the best option. Will update the yaml.

**Comment by CommanderK5** [comment]
This should be sorted now. Tested on sxeris. PR https://github.com/renderedtext/launchpad/pull/354
