### ISSUE TITLE
Document how to introduce new pages

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docs#653]
The current README and README-dev files are display deprecated information. 

We need updated information how to introduce new pages.

**Comment by Ivana-Markovic** [comment]
Where do I do that @shiroyasha ? I have created this pull request, touching only the parts that are not related to the Development section: https://github.com/semaphoreci/docs/pull/651/files

**Comment by shiroyasha** [comment]
Great! I didn't know this exists. Merging the PR into master. cc @DamjanBecirovic

**Comment by Ivana-Markovic** [comment]
Wonderful, thanks!
