### ISSUE TITLE
Document `install-package` in Semaphore 2.0 docs

### ISSUE THREAD

**Issue by mortenfyhn** [semaphoreci/docs#695]
As far as I can tell, the `install-package` command is present in the Semaphore 2.0 toolbox (I can use it in my builds). It was also present in Semaphore Classic, and documented here: https://semaphoreci.com/docs/how-to-install-dependency.html#caching-installations

But I cannot find it mentioned in the Semaphore 2.0 docs, so I'm not sure if it's deprecated or if it's just not documented yet.

**Comment by csidyel** [comment]
👋 `install-package` is deprecated in Semaphore 2.0 because it doesn't work with the cache mechanism the same way it did in Semaphore Classic.

**Comment by mortenfyhn** [comment]
Aha! Thanks, good to know. It would be useful if it would print a deprecation warning or something like that when running it.

**Comment by csidyel** [comment]
Thanks for the idea! I'll share it with my colleagues.

**Comment by Humorloos** [comment]
I just ran into this problem while trying to cache installation of gdal package using install-package as mentioned in toolbox documentation (https://docs.semaphoreci.com/reference/toolbox-reference/#install-package).

This installation significantly slows down the project's pipeline, so I would like to cache it somehow.

As `install-package` is deprecated, is there any other way to cache installed packages?
