### ISSUE TITLE
Make `redcarpet` put `target="_blank"` to all links.

### ISSUE THREAD

**Issue by mactsouk** [semaphoreci/docs#7]
Currently, all URLs in docs do not have `target="_blank"`. Please make `redcarpet` do that.

**Comment by darkofabijan** [comment]
@mactsouk why do we want this behaviour?

**Comment by mactsouk** [comment]
So that when a user clicks on a link, it will open a new browser tab or window and not leave `docs.semaphoreci.com`. Especially, when clicking on an external link.

**Comment by markoa** [comment]
Closing as "wontfix" for the time being. If there's a case when target blank really is better UX, you can write plain HTML.
