### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Baklap4** [semaphoreci/docs#741]
Currently only Linux, docker (based on linux) and MacOS is available.
Will there be a  time when windows will also be supported?

**Comment by Ivana-Markovic** [comment]
@Baklap4 - thanks for the request! That is correct and the Windows environment is not supported at the moment, but it's on our roadmap. I've added your vote for this feature request, and I'll make sure to keep you posted on the progress.

Please let me know if I can help with anything else or feel free to get in touch with our Support team at support@semaphoreci.com.

**Comment by Baklap4** [comment]
If there's anything i can do to help just reach out to me :) 

Docker based on windows (with windows containers) is also a thing :) 
Where can we view the roadmap?

**Comment by Ivana-Markovic** [comment]
Sorry for the delay @Baklap4 🙂.

This is our [roadmap](https://github.com/semaphoreci/semaphore/projects/1#card-18229917) but please note that it contains a list of features and improvements we have planned to implement in a relatively immediate future. At the moment, Windows support is on our internal roadmap and will get to the public roadmap once it gets prioritized.

As a workaround, our platform team recommends using microsoft .net containers for linux: mcr.microsoft.com/dotnet/core/sdk:2.2-bionic. Hope this helps!

**Comment by Baklap4** [comment]
Sadly we'd love to just have a windows machine since we're not actually using dotnet core or such. We'll be waiting and would love to try it out once it gets here :) This issue can now be closed

**Comment by Ivana-Markovic** [comment]
Thanks for your patience - I have recorded your request internally and will make sure to ping you here as soon as we have an update for you. Stay safe!

**Comment by Baklap4** [comment]
@Ivana-Markovic How are things going over here?

**Comment by Ivana-Markovic** [comment]
@Baklap4 it is good to hear from you, I hope you are doing well. I am afraid that not much changed here, we do plan to introduce Windows support, however, we do not have an ETA at this point still. I will make sure to reach out as soon as there's some news in this area.

**Comment by Baklap4** [comment]
@Ivana-Markovic Just going through some old issues and found this one. Any news on the Windows build environment?

**Comment by GabrielaG08** [comment]
@Baklap4 hey :) This is Gabriela, jumping in for Ivana. Wanted to kindly inform you that we are doing our best to implement this. Most probably by the end of the year it will be available. We will make sure to inform you properly once this is done. Thanks for understanding. Have a good day.
