### ISSUE TITLE
[Semaphore 2.0] Heroku auth credentials issue

### ISSUE THREAD

**Issue by marijadeversity** [semaphoreci/docs#750]
When deploying Rails app to Heroku instance, we experienced Invalid credentials error while executing command : heroku run rake db:migrate  . 
Instructions for deployment were used from this source: https://docs.semaphoreci.com/examples/heroku-deployment/ . Firstly we set SSH keys and Semaphore was connected to Heroku . 

Our list of commands used for deployment: 
            - checkout --use-cache
            - ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            - chmod 600 ~/.ssh/id_rsa_semaphore_heroku
            - ssh-add ~/.ssh/id_rsa_semaphore_heroku
            - git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
            - git remote add heroku $HEROKU_REMOTE
            - git push --force heroku $SEMAPHORE_GIT_BRANCH:master
            - heroku run rake db:migrate
            - heroku ps:restart

Error log: 

heroku run rake db:migrate

273 | ▸    Invalid credentials
275 | ▸    provided.
275 | Enter your Heroku credentials:
277 | Email: /home/semaphore/.local/share/heroku/client/bin/../7.exit code: 1 duration: 2m 34s
277 | Job Finished

**Comment by Ivana-Markovic** [comment]
👋thank you for pointing out to this, much appreciated @marijadeversity !

It would be immensely useful if you could  please send this request to support@semaphoreci.com . It will help us make sure what you have raised here gets forwarded to the right person on our team via our support channels. We look forward to hearing from you.

Stay safe!
