### ISSUE TITLE
"Incorrect SSH key format" when create a server

### ISSUE THREAD

**Issue by ronaiza-cardoso** [semaphoreci/docs#824]
I'm trying to add my SSH to the server but when I add it this error is shown:

<img width="924" alt="Screenshot 2020-07-17 at 15 25 18" src="https://user-images.githubusercontent.com/7999914/87796862-daf2dc00-c841-11ea-91ef-b08b3a62480c.png">

I've already used this key on my bitbucket account and know that the format is not wrong.

**Comment by csidyel** [comment]
@ronaiza-cardoso 👋 

It seems that the key is generated with the newer version of RSA. Such keys are not compatible with Semaphore Classic.

The easiest solution might be generating a new key in a Semaphore Classic SSH debug session. You may achieve this by running the following command and copying the output to the configuration file prompt in Semaphore web application:

```bash
ssh-keygen -f ~/.ssh/id_rsa -t rsa -N "" && cat ~/.ssh/id_rsa
```
If the issue continues, please send us a message to our support team in `support@semaphoreci.com`.
