### ISSUE TITLE
Provide info on using pip

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docs#88]
Current Python docs show use of pipenv, which is fairly new and not preinstalled.

Pip is preinstalled and common so let's have show how to use pip in dependency caching section first, before pipenv.

**Comment by mimimalizam** [comment]
`pip` installs packages to `~/.pip_download_cache` directory. On the other hand, `cache` uses `tar` and consequently `cache` doesn't remember the absolute path in every case. 

Current behavior is that cached archive is restored on the current path, from where the function is called. Atm, this can be mitigated by changing directory and running the `cache restore` or by using`mv`.

The following command sequence caches the Python packages:
```
         - cache restore py-packages
         - checkout
         - pip install -r requirements.txt
         - cd && cache store py-packages .pip_download_cache
```
